homebrew_packages:
  - composer
  - coreutils
  - composer
  - git
  - go
  - highlight
#  - nkf
  - nodenv
  - php
  - phpunit
  - python3
  - ruby
  - rbenv
  - screen
  - vim
  - zsh
  - zsh-completions
